---
title: "Hw03_dplyr_ggplot2_Part_II"
author: "Almas K."
date: '2019-09-28'
output: github_document
---
```{r load, warning=FALSE,echo=FALSE}
suppressPackageStartupMessages(library(tidyverse)) 
suppressPackageStartupMessages(library(gapminder))
```
## Task Option 2: Maximum and minimum of GDP per capita for all continents

```{r}
gapminder %>%
   group_by(continent)  %>%
  summarize(max=max(gdpPercap),min=min(gdpPercap)) %>%
  print() %>%
  ggplot()
  
```


## Task Option 5: How is life expectancy changing over time on different continents?
```{r}
gapminder %>%
   group_by(continent,year)  %>%
  arrange(year) %>%
  summarize(meanLife= mean(lifeExp)) %>%
print() %>%
  ggplot(aes( x=year,y=meanLife)) + 
  geom_point()+
  facet_wrap(. ~continent) 
```
The life expectancy of Europe and Oceania started off fairly high in the 1950s and increased to 


## Task Option 3 : Look at the spread of GDP per capita within the continents.
```{r}
gapminder %>%
   group_by(continent)  %>%
mutate(log_gdpPercap= log(gdpPercap)) %>%
  select(continent,log_gdpPercap) %>%
  arrange(log_gdpPercap) %>%
 print() %>%
  ggplot(aes(x=log_gdpPercap)) +
  geom_density() +
   facet_wrap(. ~continent) 
```


